### ISSUE TITLE
In Vue 3 not support

### ISSUE THREAD

**Issue by Khatri-Ran-Bahadur** [ZestfulNation/vue-hotel-datepicker#326]
Cannot read properties of undefined (reading '_c')
TypeError: Cannot read properties of undefined (reading '_c')
    at Proxy.render (webpack-internal:///./node_modules/vue-hotel-datepicker/dist/vueHotelDatepicker.common.js:1460:26)
    at renderComponentRoot (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:890:38)
    at ReactiveEffect.componentUpdateFn [as fn] (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5067:46)
    at ReactiveEffect.run (webpack-internal:///./node_modules/@vue/reactivity/dist/reactivity.esm-bundler.js:216:19)
    at instance.update (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5164:51)
    at setupRenderEffect (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:5172:5)
    at mountComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4986:5)
    at processComponent (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4951:9)
    at patch (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4633:11)
    at mountChildren (webpack-internal:///./node_modules/@vue/runtime-core/dist/runtime-core.esm-bundler.js:4790:7)

**Comment by matiasperrone** [comment]
The version in the PR does not work as expected.
I am working on https://github.com/ZestfulNation/vue3-hotel-datepicker for the Vue 3 Composite API version, still is a work in progress.
